---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
